/** Curriculum card hints keyed by Russian card names from CURRICULUM_SETS. */
export const CURRICULUM_HINTS = {
  ru: {
    'Рабовладельческий строй': 'Общественный строй, при котором рабы были собственностью хозяина и работали на него. Существовал в Древней Греции и Риме.',
    'Полис': 'Небольшое самостоятельное городское государство в Древней Греции. Жители полиса участвовали в общественной жизни.',
    'Демократия (Древняя Греция)': 'Власть народа: граждане собирались на народном собрании и голосовали. Наиболее известный пример — Афины.',
    'Олимпийские игры': 'Спортивные соревнования в честь Зевса в Олимпии раз в четыре года. На время игр объявлялось перемирие.',
    'Республика (Древний Рим)': 'Правление, где власть принадлежит избранным органам, а не одному правителю. В Риме республика существовала с V века до н.э.',
    'Легион': 'Основное боевое подразделение римской армии из тяжеловооружённой пехоты. Легионеры строили лагеря и сражались строем.',
    'Империя (Древний Рим)': 'Государство с властью императора и огромной территорией. Римская империя простиралась от Британии до Египта.',
    'Христианство': 'Мировая религия, возникшая в I веке на Ближнем Востоке. Со временем стала главной религией Римской империи.',
    'Варвары': 'Так римляне называли народы за пределами империи. Их нашествия ускорили падение Западной Римской империи.',
    'Феодализм': 'Система земельных и личных зависимостей в Средневековье. Сюзерен давал землю вассалу, вассал служил ему.',
    'Рыцарство': 'Военное сословие рыцарей с кодексом чести и верности сеньору. Рыцари защищали замки и участвовали в походах.',
    'Средневековье': 'Период европейской истории после падения Римской империи (V–XV вв.). Характерны феодализм, церковь и замки.',
    'Гомер': 'Древнегреческий поэт, автор «Илиады» и «Одиссеи». Его произведения рассказывают о Троянской войне.',
    'Леонид I': 'Спартанский царь, погибший в битве при Фермопилах в 480 г. до н.э. Его отряд сдерживал огромное персидское войско.',
    'Александр Македонский': 'Царь Македонии, создатель крупнейшей империи древности. Завоевал Персию, Египет и часть Индии.',
    'Аристотель': 'Великий древнегреческий философ и учёный. Был учителем Александра Македонского.',
    'Перикл': 'Афинский политик эпохи расцвета демократии. При нём построили Парфенон и укрепили влияние Афин.',
    'Гай Юлий Цезарь': 'Римский полководец и политик I века до н.э. Расширил владения Рима и стал диктатором.',
    'Октавиан Август': 'Первый римский император, принёсший мир после гражданских войн. Правил с 27 г. до н.э.',
    'Константин Великий': 'Римский император, признавший христианство. Перенёс столицу империи в Константинополь.',
    'Юстиниан I': 'Византийский император VI века. Создал свод законов и временно восстановил единство бывшей Римской империи.',
    'Карл Великий': 'Король франков, император Запада. Объединил большую часть Западной Европы и поддерживал образование.',
    'Альфред Великий': 'Король англосаксов, защищал Англию от датчан. Способствовал развитию письменности и законов.',
    'Вильгельм Завоеватель': 'Норманнский герцог, завоевавший Англию в 1066 году. После битвы при Гастингсе стал её королём.',
    'Битва при Марафоне (490 г. до н.э.)': 'Афиняне разбили персидское войско. Победа сохранила независимость греческих полисов.',
    'Битва при Фермопилах (480 г. до н.э.)': 'Небольшой отряд греков во главе с Леонидом сдерживал персов у узкого прохода. Защитники погибли, но выиграли время союзникам.',
    'Поход Александра Македонского в Азию (334–323 гг. до н.э.)': 'Александр разгромил Персию и завоевал огромные территории. Поход связал Восток и Запад.',
    'Образование Римской республики (509 г. до н.э.)': 'Римляне свергли последнего царя и установили республиканское правление. Власть перешла к сенату и магистратам.',
    'Убийство Юлия Цезаря (44 г. до н.э.)': 'Сенаторы убили Цезаря в день мартовских ид. Это вызвало новые гражданские войны в Риме.',
    'Битва при Акции (31 г. до н.э.)': 'Флот Октавиана разбил силы Марка Антония и Клеопатры. Итог — установление империи.',
    'Разделение Римской империи (395 г.)': 'Империя поделилась на Восточную и Западную части. Они управлялись разными императорами.',
    'Падение Западной Римской империи (476 г.)': 'Последний западный император был свергнут вождем остготов. Эта дата часто считается концом античности в Западной Европе.',
    'Норманнское завоевание Англии (1066 г.)': 'Вильгельм Завоеватель победил англосаксов при Гастингсе. Норманны стали правящим классом Англии.',
    'Первый крестовый поход (1096–1099 гг.)': 'Западноевропейские рыцари пошли освобождать Иерусалим от мусульман. Крестоносцы захватили город в 1099 году.',
    'Подписание Великой хартии вольностей (1215 г.)': 'Король Иоанн Безземельный ограничил свою власть перед баронами. Хартия заложила основы парламентской традиции в Англии.',
    'Осада Константинополя крестоносцами (1204 г.)': 'Крестоносцы взяли столицу Византии и грабили город. Византийская империя надолго ослабла.',
    'Версальско-Вашингтонская система': 'Международный порядок после Первой мировой войны, основанный на Версале и Вашингтонских соглашениях. Включал новые границы и режим репараций для Германии.',
    'Лига Наций': 'Международная организация, созданная после Первой мировой войны для сохранения мира. США в неё не вступили, и она не смогла предотвратить Вторую мировую.',
    'Тоталитаризм': 'Режим, при котором государство полностью контролирует общество и личную жизнь. Характерен для Германии, Италии и СССР в 1920–1930-х годах.',
    'Фашизм': 'Крайне правая тоталитарная идеология в Италии и Германии. Пропагандировала национализм, диктатуру и агрессию.',
    'Холодная война': 'Противостояние СССР и США после Второй мировой войны без прямой войны между ними. Проявлялось в гонке вооружений и соперничестве блоков.',
    'Биполярный мир': 'Мир, разделённый на два лагеря — социалистический и капиталистический. Доминировали сверхдержавы СССР и США.',
    'Деколонизация': 'Освобождение колоний азиатских и африканских народов от европейского господства. Происходило в основном после 1945 года.',
    'Организация Объединённых Наций': 'Международная организация, основанная в 1945 году для поддержания мира и сотрудничества. Штаб-квартира находится в Нью-Йорке.',
    'Европейский союз': 'Объединение европейских государств для экономической и политической интеграции. Начало — с Европейского сообщества угля и стали.',
    'Глобализация': 'Сближение экономик и культур разных стран мира. Усиливается обмен товарами, информацией и капиталом.',
    'Ядерное оружие': 'Оружие массового поражения на основе деления атомного ядра. Первые бомбы применили США в 1945 году.',
    'Международный терроризм': 'Насильственные действия групп против гражданского населения и государств. Стал важной угрозой в конце XX — начале XXI века.',
    'Вудро Вильсон': 'Президент США, предложивший «14 пунктов» и создавший Лигу Наций. Выступал за мир без аннексий после Первой мировой.',
    'Владимир Ленин': 'Руководитель большевиков, организатор Октябрьской революции 1917 года. Создал Советское государство.',
    'Иосиф Сталин': 'Советский руководитель с 1920-х годов, проводил индустриализацию и коллективизацию. Во время Великой Отечественной войны — Верховный главнокомандующий.',
    'Адольф Гитлер': 'Лидер нацистской Германии, развязавший Вторую мировую войну. Установил диктатуру и политику геноцида.',
    'Уинстон Черчилль': 'Премьер-министр Великобритании во время Второй мировой войны. Известен речами, поднимавшими дух сопротивления.',
    'Франклин Рузвельт': 'Президент США, проводивший политику «Нового курса» во время Великой депрессии. Во время войны — союзник СССР.',
    'Шарль де Голль': 'Лидер движения Сопротивления во Франции, президент после войны. Отстаивал независимость Франции.',
    'Махатма Ганди': 'Индийский лидер, боровшийся за независимость ненасильственными методами. Проводил походы и бойкоты.',
    'Нельсон Мандела': 'Борец против апартеида в ЮАР, долгие годы сидел в тюрьме. Стал первым чёрным президентом страны.',
    'Михаил Горбачёв': 'Генеральный секретарь КПСС, начавший перестройку и гласность. Политика привела к ослаблению контроля партии.',
    'Маргарет Тэтчер': 'Премьер-министр Великобритании в 1980-х, проводила либеральные экономические реформы. Известна жёсткой внешней политикой.',
    'Барак Обама': 'Президент США, первый афроамериканец на этом посту. Избран в 2008 году.',
    'Версальский мирный договор (1919 г.)': 'Мирный договор, подписанный после Первой мировой войны. Германия признала вину и понесла тяжёлые репарации.',
    'Основание Лиги Наций (1920 г.)': 'Лига Наций начала работу в Женеве. Её целью было предотвращение новых войн.',
    'Начало Великой депрессии (1929 г.)': 'Мировой экономический кризис с массовой безработицей и падением производства. Начался с краха на бирже в США.',
    'Приход Адольфа Гитлера к власти в Германии (1933 г.)': 'Гитлер стал канцлером и установил диктатуру в Германии. Началась подготовка к агрессии.',
    'Начало Второй мировой войны (1939 г.)': 'Германия напала на Польшу, началась мировая война. Вскоре в конфликт вступили многие государства.',
    'Капитуляция Германии (1945 г.)': 'Германия капитулировала безоговорочно. В Европе закончилась война 8 мая 1945 года.',
    'Образование ООН (1945 г.)': 'ООН создана для сохранения мира и безопасности. В неё вошли победители и многие другие страны.',
    'Берлинский кризис (1961 г.)': 'СССР возвёл Берлинскую стену, чтобы остановить отток населения. Кризис обострил противостояние блоков.',
    'Падение Берлинской стены (1989 г.)': 'Стена, разделявшая Берлин, была открыта. Символом стало падение коммунистических режимов в Восточной Европе.',
    'Распад СССР (1991 г.)': 'В конце 1991 года СССР прекратил существование. Образовались независимые республики, в том числе Беларусь.',
    'Теракты 11 сентября в США (2001 г.)': 'Террористы захватили самолёты и атаковали объекты в США. Погибли тысячи людей, началась борьба с терроризмом.',
    'Вступление Китая в ВТО (2001 г.)': 'Китай вступил во Всемирную торговую организацию. Это ускорило его включение в мировую экономику.',
    'Полачане': 'Восточнославянское племя, основавшее Полоцк. Жили по рекам Западной Двины и Днепра.',
    'Другвины': 'Племенной союз на территории современной Беларуси. Занимались земледелием, охотой и ремёслами.',
    'Кривичи': 'Одно из крупнейших восточнославянских племён. Их земли простирались от Прибалтики до верховьев Днепра.',
    'Полоцкое княжество': 'Древнерусское государство со столицей в Полоцке. В IX–X веках играло важную роль в регионе.',
    'Великое княжество Литовское': 'Государство литовских и белорусских земель с центром в Вильне. Было одним из крупнейших в Европе.',
    'Статут ВКЛ': 'Свод законов Великого княжества Литовского. Закреплял права шляхты и порядок суда.',
    'Литвин': 'Житель Великого княжества Литовского, говоривший на старобелорусском. Так называли местное население в источниках.',
    'Магдебургское право': 'Право городского самоуправления по немецкому образцу. Города получали суд, торговлю и выборные органы.',
    'Шляхта': 'Дворянское сословие в Речи Посполитой. Имела политические привилегии и владела землёй.',
    'Крепостное право': 'Зависимость крестьян от помещика с привязанностью к земле. Распространилось в Речи Посполитой и Российской империи.',
    'Брестская церковная уния': 'Союз православных и униатских церквей под властью папы. Принят в Бресте в 1596 году.',
    'Речь Посполитая': 'Объединённое государство Польши и Великого княжества Литовского. Существовало с 1569 по конец XVIII века.',
    'Рогнёда': 'Жена князя Изяслава, ставшая монахиней после убийства мужа. Символ стойкости в полоцкой истории.',
    'Ефросинья Полоцкая': 'Полоцкая княжна и святая, основала монастырь. Прославилась подвижничеством и просветительской деятельностью.',
    'Франциск Скорина': 'Первый белорусский книгопечатник и гуманист. Издал Библию и другие книги на белорусском языке.',
    'Миндовг': 'Первый король Литвы, объединил литовские земли. Крестился и укрепил государство.',
    'Витовт': 'Великий князь литовский, расширил владения до Чёрного моря. Соперничал с ордынцами и Тевтонским орденом.',
    'Альгерд': 'Великий князь, усилил Литву и боролся с Тевтонским орденом. Отец Ягайло.',
    'Ягайло': 'Великий князь литовский и король Польши. Заключил Кревскую унию с Польшей.',
    'Лев Сапега': 'Канцлер ВКЛ, один из составителей Статута 1588 года. Защищал права шляхты и государство.',
    'Николай Радзивилл Чёрный': 'Магнат и военачальник, гетман Великого княжества. Участвовал в войнах Речи Посполитой.',
    'Симеон Полоцкий': 'Писатель и проповедник XVII века, воспитатель царевича Алексея. Автор поучительных произведений.',
    'Тадеуш Костюшко': 'Польский и американский военный, герой восстания 1794 года. Сражался за независимость Польши.',
    'Кастусь Калиновский': 'Руководитель восстания 1863–1864 годов на белорусских землях. Казнён царским правительством.',
    'Образование Полоцкого княжества (IX в.)': 'Полоцкое княжество возникло в IX веке как центр восточнославянских земель. Здесь сложилась древняя государственность.',
    'Крещение Полоцка (988 г.)': 'Князь Брачислав принял христианство от Византии. Крещение укрепило связи Полоцка с восточным миром.',
    'Строительство Софийского собора в Полоцке (XI в.)': 'Собор стал духовным и культурным центром Полоцка. Один из древнейших памятников архитектуры Беларуси.',
    'Объединение литовских земель при Миндовге (XIII в.)': 'Миндовг объединил племена и создал государство. В 1253 году получил королевскую корону.',
    'Битва на реке Воже (1378 г.)': 'Литовские войска разбили ордынцев на реке Воже. Победа укрепила независимость Великого княжества.',
    'Грюнвальдская битва (1410 г.)': 'Объединённые силы Польши и Литвы разгромили Тевтонский орден. Крупная победа в Грюнвальде.',
    'Привилегия Вильно (1387 г.)': 'Великий князь Ягайло даровал католичеству привилегии в Литве. Это сблизило Литву с христианской Европой.',
    'Принятие Статута ВКЛ (1529 г.)': 'Принят первый Статут — основной закон ВКЛ. В нём закрепились права подданных и шляхты.',
    'Люблинская уния (1569 г.)': 'Польша и Великое княжество Литовское объединились в одно государство. Образовалась Речь Посполитая.',
    'Брестская церковная уния (1596 г.)': 'Часть православных перешла в унию с Римом. Цель — укрепить церковь и государство.',
    'Битва под Оршей (1514 г.)': 'Войска ВКЛ разбили московитов под Оршей. Победа укрепила оборону западных границ.',
    'Первый раздел Речи Посполитой (1772 г.)': 'Россия, Пруссия и Австрия отторгли часть земель Речи Посполитой. Начался раздел слабевшего государства.',
    'Белорусская народная республика': 'Первое белорусское государство, провозглашённое в 1918 году. Существовало недолго, но символизировало стремление к независимости.',
    'Западная Беларусь': 'Земли, вошедшие в состав Польши между мировыми войнами. В 1939 году воссоединились с БССР.',
    'Белорусская Советская Социалистическая Республика': 'Белорусская республика в составе СССР с 1919 года. Столица — Минск.',
    'Коллективизация': 'Объединение крестьянских хозяйств в колхозы в СССР. Сопровождалось ускоренной индустриализацией и трудностями в деревне.',
    'Великая Отечественная война': 'Война СССР против нацистской Германии 1941–1945 годов. На территории Беларуси шли тяжёлые бои и оккупация.',
    'Партизанское движение': 'Борьба партизан и подпольщиков против оккупантов. В Беларуси действовали крупные партизанские соединения.',
    'Операция «Багратион»': 'Крупное наступление Красной Армии летом 1944 года. Освободило Беларусь от немецких войск.',
    'Перестройка': 'Политика обновления в СССР при Горбачёве. Включала гласность и расширение экономической самостоятельности.',
    'Декларация о государственном суверенитете': 'Верховный Совет БССР провозгласил верховенство белорусских законов. Важный шаг к независимости.',
    'Независимость Республики Беларусь': 'Беларусь провозгласила суверенитет и вышла из состава СССР. С 1991 года — самостоятельное государство.',
    'Союзное государство': 'Союз Беларуси и России с общими органами. Создан по договору 1999 года.',
    'Западная интеграция': 'Сближение Беларуси с европейскими институтами и рынками. Включает торговлю, договоры и сотрудничество.',
    'Вацлав Адамович': 'Деятель белорусского национального движения начала XX века. Участвовал в создании Народной республики.',
    'Цихан Часноух': 'Председатель Белорусской народной республики в 1918 году. Один из организаторов провозглашения независимости.',
    'Янка Купала': 'Классик белорусской литературы, поэт и драматург. Писал о судьбе народа и родной земле.',
    'Якуб Колас': 'Классик белорусской литературы, прозаик и поэт. Автор «Сымона-музыканта» и других произведений.',
    'Пётр Машэраў': 'Партийный и государственный деятель БССР, первый секретарь ЦК. Руководил республикой в послевоенные годы.',
    'Константин Заслонов': 'Советский партизан, организатор подполья в оккупации. Погиб в борьбе с фашистами.',
    'Пётр Крапивницкий': 'Театральный деятель, основатель белорусского профессионального театра. Руководил труппой в Минске.',
    'Станислав Шушкевич': 'Председатель Верховного Совета БССР, подписал Беловежские соглашения. Стал первым руководителем независимой Беларуси.',
    'Александр Лукашенко': 'Президент Беларуси с 1994 года. Избран на всеобщих выборах.',
    'Зенон Позняк': 'Политик и общественный деятель, сооснователь Белорусского народного фронта. Выступал за независимость и демократические реформы.',
    'Михась Клімковіч': 'Поэт и общественный деятель, участник движения за независимость. Автор стихов о родине.',
    'Владимир Некляевич': 'Поэт, кандидат в президенты 2010 года. Известен гражданской лирикой.',
    'Провозглашение Белорусской народной республики (1918 г.)': 'БНР провозглашена в Минске 25 марта 1918 года. Первый акт белорусской государственности в XX веке.',
    'Образование БССР (1919 г.)': 'Советская власть установила БССР в январе 1919 года. Республика вошла в состав СССР.',
    'Воссоединение Западной Беларуси с БССР (1939 г.)': 'Западная Беларусь присоединена к БССР по пакту 1939 года. Население получило советское гражданство.',
    'Начало Великой Отечественной войны на территории БССР (1941 г.)': '22 июня 1941 года Германия напала на СССР. Беларусь оказалась на линии фронта и в оккупации.',
    'Операция «Багратион» (1944 г.)': 'Летом 1944 года Красная Армия освободила большую часть Беларуси. Операция ускорила изгнание оккупантов.',
    'Освобождение Минска (1944 г.)': '3 июля 1944 года советские войска вошли в Минск. Город был разрушен, началось восстановление.',
    'Чернобыльская катастрофа на территории БССР (1986 г.)': 'Авария на ЧАЭС затронула Гомельскую и Могилёвскую области. Тысячи людей были эвакуированы.',
    'Принятие Декларации о государственном суверенитете (1990 г.)': 'Верховный Совет принял декларацию о суверенитете в 1990 году. Законы БССР объявлены высшими на её территории.',
    'Провозглашение независимости Республики Беларусь (1991 г.)': '19 сентября 1991 года провозглашена независимость. Беларусь стала суверенным государством.',
    'Первые президентские выборы в Беларуси (1994 г.)': 'Александр Лукашенко избран президентом в 1994 году. Прошли первые прямые всенародные выборы главы государства.',
    'Референдум об изменении Конституции (1996 г.)': 'На референдуме 1996 года расширили полномочия президента. Изменили конституцию по итогам голосования.',
  },
  en: {
    'Рабовладельческий строй': 'A social system where slaves were the property of their owner and worked for him. It existed in ancient Greece and Rome.',
    'Полис': 'A small independent city-state in ancient Greece. Citizens took part in public life.',
    'Демократия (Древняя Греция)': 'Rule by the people: citizens met in assemblies and voted. Athens is the best-known example.',
    'Олимпийские игры': 'Athletic contests held every four years in Olympia in honor of Zeus. A truce was declared during the games.',
    'Республика (Древний Рим)': 'A form of government where power belongs to elected bodies, not one ruler. The Roman Republic began in the 5th century BCE.',
    'Легион': 'The main combat unit of the Roman army made up of heavy infantry. Legionaries fought in formation and built camps.',
    'Империя (Древний Рим)': 'A state ruled by an emperor with vast territory. The Roman Empire stretched from Britain to Egypt.',
    'Христианство': 'A world religion that arose in the 1st century in the Middle East. It later became the main religion of the Roman Empire.',
    'Варвары': 'What Romans called peoples outside the empire. Their invasions helped bring down the Western Roman Empire.',
    'Феодализм': 'A system of land and personal ties in the Middle Ages. A lord granted land to a vassal who served him.',
    'Рыцарство': 'A military estate of knights bound by honor and loyalty to their lord. Knights defended castles and joined campaigns.',
    'Средневековье': 'The period of European history after the fall of Rome (5th–15th centuries). Feudalism, the Church, and castles were typical.',
    'Гомер': 'An ancient Greek poet, author of the Iliad and the Odyssey. His works tell of the Trojan War.',
    'Леонид I': 'A Spartan king who died at Thermopylae in 480 BCE. His small force held back a huge Persian army.',
    'Александр Македонский': 'King of Macedon who built the largest empire of antiquity. He conquered Persia, Egypt, and part of India.',
    'Аристотель': 'A great ancient Greek philosopher and scholar. He taught Alexander the Great.',
    'Перикл': 'An Athenian leader at the height of democracy. The Parthenon was built during his time.',
    'Гай Юлий Цезарь': 'A Roman general and politician of the 1st century BCE. He expanded Rome’s lands and became dictator.',
    'Октавиан Август': 'The first Roman emperor who brought peace after civil wars. He ruled from 27 BCE.',
    'Константин Великий': 'A Roman emperor who recognized Christianity. He moved the capital to Constantinople.',
    'Юстиниан I': 'A 6th-century Byzantine emperor. He codified laws and briefly restored unity to the former Roman lands.',
    'Карл Великий': 'King of the Franks and emperor of the West. He united much of Western Europe and promoted learning.',
    'Альфред Великий': 'An Anglo-Saxon king who defended England from the Danes. He encouraged literacy and law.',
    'Вильгельм Завоеватель': 'A Norman duke who conquered England in 1066. He became king after the Battle of Hastings.',
    'Битва при Марафоне (490 г. до н.э.)': 'Athenians defeated a Persian army. The victory preserved the independence of the Greek city-states.',
    'Битва при Фермопилах (480 г. до н.э.)': 'A small Greek force led by Leonidas held the Persians at a narrow pass. The defenders died but gained time for allies.',
    'Поход Александра Македонского в Азию (334–323 гг. до н.э.)': 'Alexander crushed Persia and conquered vast lands. The campaign linked East and West.',
    'Образование Римской республики (509 г. до н.э.)': 'Romans overthrew the last king and set up a republic. Power passed to the Senate and magistrates.',
    'Убийство Юлия Цезаря (44 г. до н.э.)': 'Senators killed Caesar on the Ides of March. New civil wars broke out in Rome.',
    'Битва при Акции (31 г. до н.э.)': 'Octavian’s fleet defeated the forces of Mark Antony and Cleopatra. The result was the rise of the empire.',
    'Разделение Римской империи (395 г.)': 'The empire was split into eastern and western parts. Each had its own emperor.',
    'Падение Западной Римской империи (476 г.)': 'The last western emperor was deposed by a Gothic leader. This date often marks the end of antiquity in Western Europe.',
    'Норманнское завоевание Англии (1066 г.)': 'William the Conqueror defeated the Anglo-Saxons at Hastings. Normans became the ruling class of England.',
    'Первый крестовый поход (1096–1099 гг.)': 'Western European knights marched to free Jerusalem from Muslim rule. Crusaders took the city in 1099.',
    'Подписание Великой хартии вольностей (1215 г.)': 'King John limited his power before the barons. The charter laid foundations for parliament in England.',
    'Осада Константинополя крестоносцами (1204 г.)': 'Crusaders seized the Byzantine capital and looted the city. The empire was weakened for a long time.',
    'Версальско-Вашингтонская система': 'The international order after World War I based on Versailles and Washington agreements. It set new borders and reparations for Germany.',
    'Лига Наций': 'An international body founded after World War I to keep peace. The USA did not join, and it failed to stop World War II.',
    'Тоталитаризм': 'A regime where the state controls society and private life completely. Typical of Germany, Italy, and the USSR in the 1920s–1930s.',
    'Фашизм': 'A far-right totalitarian ideology in Italy and Germany. It promoted nationalism, dictatorship, and aggression.',
    'Холодная война': 'Rivalry between the USSR and the USA after World War II without direct war between them. It included an arms race and bloc rivalry.',
    'Биполярный мир': 'A world divided into socialist and capitalist camps. The superpowers were the USSR and the USA.',
    'Деколонизация': 'Liberation of Asian and African colonies from European rule. It happened mainly after 1945.',
    'Организация Объединённых Наций': 'An international organization founded in 1945 to keep peace and cooperation. Its headquarters are in New York.',
    'Европейский союз': 'Union of European states for economic and political integration. It began with the European Coal and Steel Community.',
    'Глобализация': 'Growing economic and cultural ties among countries worldwide. Trade, information, and capital flow more freely.',
    'Ядерное оружие': 'Weapons of mass destruction based on splitting the atomic nucleus. The first bombs were used by the USA in 1945.',
    'Международный терроризм': 'Violent acts by groups against civilians and states. It became a major threat in the late 20th and early 21st centuries.',
    'Вудро Вильсон': 'US president who proposed the Fourteen Points and helped create the League of Nations. He sought peace without annexations after World War I.',
    'Владимир Ленин': 'Leader of the Bolsheviks and organizer of the 1917 October Revolution. He founded the Soviet state.',
    'Иосиф Сталин': 'Soviet leader from the 1920s who carried out industrialization and collectivization. He was supreme commander in World War II.',
    'Адольф Гитлер': 'Leader of Nazi Germany who started World War II. He established dictatorship and genocide.',
    'Уинстон Черчилль': 'British prime minister during World War II. His speeches rallied resistance.',
    'Франклин Рузвельт': 'US president whose New Deal fought the Great Depression. He was an ally of the USSR in the war.',
    'Шарль де Голль': 'Leader of the French Resistance and postwar president. He defended France’s independence.',
    'Махатма Ганди': 'Indian leader who fought for independence by nonviolent methods. He led marches and boycotts.',
    'Нельсон Мандела': 'Fighter against apartheid in South Africa who spent years in prison. He became the country’s first Black president.',
    'Михаил Горбачёв': 'General Secretary of the CPSU who began perestroika and glasnost. His policies weakened party control.',
    'Маргарет Тэтчер': 'British prime minister in the 1980s who carried out liberal economic reforms. She pursued a firm foreign policy.',
    'Барак Обама': 'US president, the first African American in the office. Elected in 2008.',
    'Версальский мирный договор (1919 г.)': 'Peace treaty signed after World War I. Germany admitted guilt and paid heavy reparations.',
    'Основание Лиги Наций (1920 г.)': 'The League of Nations began work in Geneva. Its aim was to prevent new wars.',
    'Начало Великой депрессии (1929 г.)': 'A global economic crisis with mass unemployment and falling output. It began with a stock market crash in the USA.',
    'Приход Адольфа Гитлера к власти в Германии (1933 г.)': 'Hitler became chancellor and established dictatorship in Germany. Aggression followed.',
    'Начало Второй мировой войны (1939 г.)': 'Germany attacked Poland and a world war began. Many states soon joined the conflict.',
    'Капитуляция Германии (1945 г.)': 'Germany surrendered unconditionally. The war in Europe ended on 8 May 1945.',
    'Образование ООН (1945 г.)': 'The UN was created to keep peace and security. Victors and many other states joined.',
    'Берлинский кризис (1961 г.)': 'The USSR built the Berlin Wall to stop people leaving. The crisis sharpened bloc rivalry.',
    'Падение Берлинской стены (1989 г.)': 'The wall dividing Berlin was opened. It symbolized the fall of communist regimes in Eastern Europe.',
    'Распад СССР (1991 г.)': 'At the end of 1991 the USSR ceased to exist. Independent republics emerged, including Belarus.',
    'Теракты 11 сентября в США (2001 г.)': 'Terrorists hijacked planes and attacked targets in the USA. Thousands died and a global fight against terrorism began.',
    'Вступление Китая в ВТО (2001 г.)': 'China joined the World Trade Organization. This sped its integration into the world economy.',
    'Полачане': 'An East Slavic tribe that founded Polotsk. They lived along the Western Dvina and Dnieper.',
    'Другвины': 'A tribal union on the lands of modern Belarus. They farmed, hunted, and crafted goods.',
    'Кривичи': 'One of the largest East Slavic tribes. Their lands stretched from the Baltic to the upper Dnieper.',
    'Полоцкое княжество': 'An early East Slavic state with its capital in Polotsk. It played a major regional role in the 9th–10th centuries.',
    'Великое княжество Литовское': 'A state of Lithuanian and Belarusian lands centered in Vilnius. It was one of the largest countries in Europe.',
    'Статут ВКЛ': 'The legal code of the Grand Duchy of Lithuania. It defined the rights of the nobility and courts.',
    'Литвин': 'An inhabitant of the Grand Duchy who spoke Old Belarusian. Sources used this name for the local population.',
    'Магдебургское право': 'Town self-government modeled on German law. Towns gained courts, trade rights, and elected bodies.',
    'Шляхта': 'The noble estate in the Polish–Lithuanian Commonwealth. Nobles had political privileges and owned land.',
    'Крепостное право': 'Peasants bound to the landlord and the land. It spread in the Commonwealth and the Russian Empire.',
    'Брестская церковная уния': 'A union of Orthodox and Uniate churches under the pope. Adopted in Brest in 1596.',
    'Речь Посполитая': 'The united state of Poland and the Grand Duchy of Lithuania. It existed from 1569 until the late 18th century.',
    'Рогнёда': 'Wife of Prince Izyaslav who became a nun after her husband’s murder. A symbol of steadfastness in Polotsk history.',
    'Ефросинья Полоцкая': 'A Polotsk princess and saint who founded a convent. Known for ascetic life and teaching.',
    'Франциск Скорина': 'The first Belarusian printer and humanist. He published the Bible and other books in Belarusian.',
    'Миндовг': 'The first king of Lithuania who united Lithuanian lands. He was baptized and strengthened the state.',
    'Витовт': 'Grand Duke of Lithuania who expanded lands to the Black Sea. He rivaled the Horde and the Teutonic Order.',
    'Альгерд': 'Grand Duke who strengthened Lithuania and fought the Teutonic Order. Father of Jogaila.',
    'Ягайло': 'Grand Duke of Lithuania and king of Poland. He signed the Union of Krewo with Poland.',
    'Лев Сапега': 'Chancellor of the GDL and co-author of the 1588 Statute. He defended noble rights and the state.',
    'Николай Радзивилл Чёрный': 'A magnate and military leader, hetman of the Grand Duchy. He fought in the Commonwealth’s wars.',
    'Симеон Полоцкий': 'A 17th-century writer and preacher, tutor of Tsarevich Alexei. He wrote moral works.',
    'Тадеуш Костюшко': 'A Polish and American soldier, hero of the 1794 uprising. He fought for Poland’s independence.',
    'Кастусь Калиновский': 'Leader of the 1863–1864 uprising on Belarusian lands. Executed by the tsarist government.',
    'Образование Полоцкого княжества (IX в.)': 'The Principality of Polotsk arose in the 9th century as a center of East Slavic lands. Early statehood formed here.',
    'Крещение Полоцка (988 г.)': 'Prince Bryachislav accepted Christianity from Byzantium. Baptism strengthened Polotsk’s ties with the East.',
    'Строительство Софийского собора в Полоцке (XI в.)': 'The cathedral became the spiritual and cultural center of Polotsk. It is one of Belarus’s oldest architectural monuments.',
    'Объединение литовских земель при Миндовге (XIII в.)': 'Mindaugas united tribes and created a state. In 1253 he received a royal crown.',
    'Битва на реке Воже (1378 г.)': 'Lithuanian forces defeated the Horde on the Vikhra River. The victory strengthened the Grand Duchy’s independence.',
    'Грюнвальдская битва (1410 г.)': 'Combined Polish and Lithuanian forces crushed the Teutonic Order. A major victory at Grunwald.',
    'Привилегия Вильно (1387 г.)': 'Grand Duke Jogaila granted privileges to Catholicism in Lithuania. This drew Lithuania closer to Christian Europe.',
    'Принятие Статута ВКЛ (1529 г.)': 'The first Statute was adopted as the main law of the GDL. It secured subjects’ and nobles’ rights.',
    'Люблинская уния (1569 г.)': 'Poland and the Grand Duchy united into one state. The Polish–Lithuanian Commonwealth was formed.',
    'Брестская церковная уния (1596 г.)': 'Part of the Orthodox Church entered union with Rome. The goal was to strengthen church and state.',
    'Битва под Оршей (1514 г.)': 'GDL troops defeated Muscovites at Orsha. The victory strengthened defense of the western border.',
    'Первый раздел Речи Посполитой (1772 г.)': 'Russia, Prussia, and Austria seized part of the Commonwealth’s lands. The partition of the weakening state began.',
    'Белорусская народная республика': 'The first Belarusian state proclaimed in 1918. It was short-lived but showed the drive for independence.',
    'Западная Беларусь': 'Lands that were part of Poland between the world wars. In 1939 they reunited with the BSSR.',
    'Белорусская Советская Социалистическая Республика': 'The Belarusian republic within the USSR from 1919. Its capital is Minsk.',
    'Коллективизация': 'Merging peasant farms into collective farms in the USSR. It went with rapid industrialization and hardship in the countryside.',
    'Великая Отечественная война': 'The USSR’s war against Nazi Germany, 1941–1945. Heavy fighting and occupation took place in Belarus.',
    'Партизанское движение': 'Partisans and underground fighters resisted the occupiers. Large partisan units operated in Belarus.',
    'Операция «Багратион»': 'A major Red Army offensive in summer 1944. It liberated Belarus from German forces.',
    'Перестройка': 'Gorbachev’s policy of renewal in the USSR. It included glasnost and more economic autonomy.',
    'Декларация о государственном суверенитете': 'The BSSR Supreme Soviet proclaimed the supremacy of Belarusian laws. A key step toward independence.',
    'Независимость Республики Беларусь': 'Belarus proclaimed sovereignty and left the USSR. Since 1991 it has been an independent state.',
    'Союзное государство': 'A union of Belarus and Russia with shared bodies. Created by a 1999 treaty.',
    'Западная интеграция': 'Belarus drawing closer to European institutions and markets. It includes trade, treaties, and cooperation.',
    'Вацлав Адамович': 'A figure in the Belarusian national movement in the early 20th century. He took part in creating the People’s Republic.',
    'Цихан Часноух': 'Chairman of the Belarusian People’s Republic in 1918. One of the organizers of the proclamation of independence.',
    'Янка Купала': 'A classic of Belarusian literature, poet and playwright. He wrote about the fate of the people and native land.',
    'Якуб Колас': 'A classic of Belarusian literature, novelist and poet. Author of Symon the Musician and other works.',
    'Пётр Машэраў': 'Party and state leader of the BSSR, first secretary of the Central Committee. He led the republic in the postwar years.',
    'Константин Заслонов': 'A Soviet partisan who organized underground resistance. He died fighting the occupiers.',
    'Пётр Крапивницкий': 'A theater figure who founded professional Belarusian theater. He led a troupe in Minsk.',
    'Станислав Шушкевич': 'Chairman of the BSSR Supreme Soviet who signed the Belovezh Accords. He became the first leader of independent Belarus.',
    'Александр Лукашенко': 'President of Belarus since 1994. Elected in nationwide elections.',
    'Зенон Позняк': 'Politician and public figure, co-founder of the Belarusian Popular Front. He advocated independence and democratic reform.',
    'Михась Клімковіч': 'Poet and public figure in the independence movement. He wrote verses about his homeland.',
    'Владимир Некляевич': 'Poet and presidential candidate in 2010. Known for civic poetry.',
    'Провозглашение Белорусской народной республики (1918 г.)': 'The BNR was proclaimed in Minsk on 25 March 1918. The first act of Belarusian statehood in the 20th century.',
    'Образование БССР (1919 г.)': 'Soviet power established the BSSR in January 1919. The republic joined the USSR.',
    'Воссоединение Западной Беларуси с БССР (1939 г.)': 'Western Belarus was annexed to the BSSR under the 1939 pact. People received Soviet citizenship.',
    'Начало Великой Отечественной войны на территории БССР (1941 г.)': 'On 22 June 1941 Germany attacked the USSR. Belarus was on the front line and under occupation.',
    'Операция «Багратион» (1944 г.)': 'In summer 1944 the Red Army liberated most of Belarus. The operation speeded the expulsion of occupiers.',
    'Освобождение Минска (1944 г.)': 'On 3 July 1944 Soviet troops entered Minsk. The city was ruined and rebuilding began.',
    'Чернобыльская катастрофа на территории БССР (1986 г.)': 'The Chernobyl accident affected Gomel and Mogilev regions. Thousands were evacuated.',
    'Принятие Декларации о государственном суверенитете (1990 г.)': 'The Supreme Soviet adopted a sovereignty declaration in 1990. BSSR laws were declared supreme on its territory.',
    'Провозглашение независимости Республики Беларусь (1991 г.)': 'Independence was proclaimed on 19 September 1991. Belarus became a sovereign state.',
    'Первые президентские выборы в Беларуси (1994 г.)': 'Alexander Lukashenko was elected president in 1994. The first direct nationwide election of the head of state.',
    'Референдум об изменении Конституции (1996 г.)': 'A 1996 referendum expanded presidential powers. The constitution was changed by the vote.',
  },
  be: {
    'Рабовладельческий строй': 'Грамадскі лад, пры якім рабы былі ўласнасцю гаспадара і працавалі на яго. Існаваў у Старажытнай Грэцыі і Рыме.',
    'Полис': 'Невялікае самастойнае гарадское дзяржава ў Старажытнай Грэцыі. Жыхары поліса ўдзельнічалі ў грамадскай жыцці.',
    'Демократия (Древняя Греция)': 'Улада народа: грамадзяне збіраліся на народным сходзе і галасавалі. Найвядомейшы прыклад — Афіны.',
    'Олимпийские игры': 'Спартыўныя спаборніцтвы ў гонар Зеўса ў Алімпіі раз у чатыры гады. На час гульняў абвяшчалі перамір’е.',
    'Республика (Древний Рим)': 'Правіленне, дзе ўлада належыць абраным органам, а не аднаму праўніку. У Рыме рэспубліка існавала з V ст. да н.э.',
    'Легион': 'Асноўнае баявое падраздленне рымскай арміі з цяжкай пяхоты. Легіёнеры будавалі лагеры і змагаліся строем.',
    'Империя (Древний Рим)': 'Дзяржава з уладай імператара і вялізным тэрыторыяй. Рымская імперыя простяглася ад Брытаніі да Егіпта.',
    'Христианство': 'Сусветная рэлігія, што ўзнікла ў I ст. на Блізкім Усходзе. З часам стала галоўнай рэлігіяй Рымскай імперыі.',
    'Варвары': 'Так рымляне называлі народы за межамі імперыі. Іх нашэствы паскорылі падзенне Заходняй Рымскай імперыі.',
    'Феодализм': 'Сістэма зямельных і асабістых залежнасцей у Сярэдневеччы. Сюзерэн даваў зямлю васалу, васал служыў яму.',
    'Рыцарство': 'Ваеннае саслоўе рыцароў з кодэксам гонару і вернасці сеньёру. Рыцары абаранялі замкі і ўдзельнічалі ў паходах.',
    'Средневековье': 'Перыяд еўрапейскай гісторыі пасля падзення Рыма (V–XV стст.). Характэрны феадалізм, царква і замкі.',
    'Гомер': 'Старажытнагрэцкі паэт, аўтар «Іліады» і «Адысеі». Яго творы расказваюць пра Траянскую вайну.',
    'Леонид I': 'Спартанскі цар, загінуўшы ў бітве пры Фермапілах у 480 г. да н.э. Яго атрад стрымоўваў вялікае персідскае войска.',
    'Александр Македонский': 'Цар Македоніі, стваральнік найбольшай імперыі антычнасці. Заваяваў Персію, Егіпет і частку Індыі.',
    'Аристотель': 'Вялікі старажытнагрэцкі філосаф і вучоны. Быў настаўнікам Аляксандра Македонскага.',
    'Перикл': 'Афінскі палітык эпохі росквіту дэмакратыі. Пры ім пабудавалі Парфенон і ўмацавалі ўплыў Афін.',
    'Гай Юлий Цезарь': 'Рымскі палкаводца і палітык I ст. да н.э. Пашырыў уладанні Рыма і стаў дыктатарам.',
    'Октавиан Август': 'Першы рымскі імператар, які прынёс мір пасля грамадзянскіх войнаў. Праўліў з 27 г. да н.э.',
    'Константин Великий': 'Рымскі імператар, які прызнаў хрысціянства. Перанёс сталіцу імперыі ў Канстанцінопаль.',
    'Юстиниан I': 'Візантыйскі імператар VI ст. Стварыў звод законаў і часова аднавіў адзінства былых рымскіх зямель.',
    'Карл Великий': 'Кароль франкаў, імператар Захаду. Аб’яднаў большую частку Заходняй Еўропы і падтрымліваў адукацыю.',
    'Альфред Великий': 'Кароль англасаксаў, які абараняў Англію ад датчан. Спрыяў развіццю пісьменнасці і законаў.',
    'Вильгельм Завоеватель': 'Нарманскі герцаг, які заваяваў Англію ў 1066 годзе. Пасля бітвы пры Гастынгсе стаў яе каралём.',
    'Битва при Марафоне (490 г. до н.э.)': 'Афіняне разбілі персідскае войска. Перамога захавала незалежнасць грэцкіх полісаў.',
    'Битва при Фермопилах (480 г. до н.э.)': 'Невялікі атрад грэкаў на чале з Леанідам стрымоўваў персаў у вузкім праходзе. Абаронцы загінулі, але выйгралі час саюзнікам.',
    'Поход Александра Македонского в Азию (334–323 гг. до н.э.)': 'Аляксандр разграміў Персію і заваяваў вялізныя тэрыторыі. Паход звязаў Усход і Захад.',
    'Образование Римской республики (509 г. до н.э.)': 'Рымляне скінулі апошняга цара і ўсталявалі рэспубліканскае правіленне. Улада перайшла да сената і магістратаў.',
    'Убийство Юлия Цезаря (44 г. до н.э.)': 'Сенатары забілі Цэзара ў дзень сакавіцкіх ід. Гэта выклікала новыя грамадзянскія войны ў Рыме.',
    'Битва при Акции (31 г. до н.э.)': 'Флот Октавіяна разбіў сілы Марка Антонія і Клеапатры. Вынік — устанаўленне імперыі.',
    'Разделение Римской империи (395 г.)': 'Імперыя падзялілася на Усходнюю і Заходнюю часткі. Імі кіравалі розныя імператары.',
    'Падение Западной Римской империи (476 г.)': 'Апошні заходні імператар быў скінуты вождам остготаў. Гэтая дата часта лічыцца канцом антычнасці ў Заходняй Еўропе.',
    'Норманнское завоевание Англии (1066 г.)': 'Вільгельм Заваёўнік перамог англасаксаў пры Гастынгсе. Нарманы сталі кіруючым класам Англіі.',
    'Первый крестовый поход (1096–1099 гг.)': 'Заходнеэўрапейскія рыцары пайшлі вызваляць Іерусалім ад мусульман. Крыжакі захапілі горад у 1099 годзе.',
    'Подписание Великой хартии вольностей (1215 г.)': 'Кароль Іаан Безземельны абмежаваў сваю ўладу перад баронамі. Хартыя заклала асновы парламентскай традыцыі ў Англіі.',
    'Осада Константинополя крестоносцами (1204 г.)': 'Крыжакі ўзялі сталіцу Візантыі і разграбілі горад. Візантыйская імперыя надоўга аслабла.',
    'Версальско-Вашингтонская система': 'Міжнародны парадак пасля Першай сусветнай вайны, заснаваны на Версалі і Вашынгтонскіх пагадненнях. Уключаў новыя мяжы і рэпарацыі для Германіі.',
    'Лига Наций': 'Міжнародная арганізацыя, створаная пасля Першай сусветнай для захавання міру. ЗША не ўступілі, і яна не перашкодзіла Другой сусветнай.',
    'Тоталитаризм': 'Рэжым, пры якім дзяржава поўнасцю кантралюе грамадства і асабістае жыццё. Характэрны для Германіі, Італіі і СССР у 1920–1930-х.',
    'Фашизм': 'Крайне правая таталітарная ідэалогія ў Італіі і Германіі. Прапагандавала нацыяналізм, дыктатуру і агрэсію.',
    'Холодная война': 'Супрацьстаянне СССР і ЗША пасля Другой сусветнай без прамой вайны паміж імі. Праяўлялася ў гонцы ўзбраенняў і суперніцтве блокаў.',
    'Биполярный мир': 'Свет, падзелены на два лагеры — сацыялістычны і капіталістычны. Дамінавалі звышдзяржавы СССР і ЗША.',
    'Деколонизация': 'Вызваленне калоній азіяцкіх і афрыканскіх народаў ад еўрапейскага панавання. Адбылося ў асноўным пасля 1945 года.',
    'Организация Объединённых Наций': 'Міжнародная арганізацыя, заснаваная ў 1945 годзе для захавання міру і супрацоўніцтва. Штаб-кватэра ў Нью-Ёрку.',
    'Европейский союз': 'Аб’яднанне еўрапейскіх дзяржаў для эканамічнай і палітычнай інтэграцыі. Пачатак — з Еўрапейскай супольнасці вуглю і сталі.',
    'Глобализация': 'Збліжэнне эканомік і культур розных краін свету. Узмацняецца абмен таварамі, інфармацыяй і капіталам.',
    'Ядерное оружие': 'Зброя масавага паражэння на аснове падзелу атамнага ядра. Першыя бомбы прымянілі ЗША ў 1945 годзе.',
    'Международный терроризм': 'Насільніцкія дзеянні груп супраць мірнага насельніцтва і дзяржаў. Сталі важнай пагрозай у канцы XX — пачатку XXI ст.',
    'Вудро Вильсон': 'Прэзідэнт ЗША, які прапанаваў «14 пунктаў» і стварыў Лігу Нацый. Выступаў за мір без анэксій пасля Першай сусветнай.',
    'Владимир Ленин': 'Кіраўнік бальшавікаў, арганізатар Кастрычніцкай рэвалюцыі 1917 года. Стварыў Савецкую дзяржаву.',
    'Иосиф Сталин': 'Савецкі кіраўнік з 1920-х, праводзіў індустрыялізацыю і калектывізацыю. У Вялікую Айчынную вайну — Вярхоўны галоўнакамандуючы.',
    'Адольф Гитлер': 'Лідар нацысцкай Германіі, які развязаў Другую сусветную вайну. Устанавіў дыктатуру і палітыку генацыду.',
    'Уинстон Черчилль': 'Прэм’ер-міністр Вялікабрытаніі ў часы Другой сусветнай. Вядомы прамовамі, якія ўздымалі дух супраціву.',
    'Франклин Рузвельт': 'Прэзідэнт ЗША, які праводзіў палітыку «Новага курсу» ў часы Вялікай дэпрэсіі. У вайне — саюзнік СССР.',
    'Шарль де Голль': 'Лідар руху Супраціву ў Францыі, прэзідэнт пасля вайны. Абараняў незалежнасць Францыі.',
    'Махатма Ганди': 'Індыйскі лідар, які змагаўся за незалежнасць ненасільніцкімі метадамі. Праводзіў паходы і байкоты.',
    'Нельсон Мандела': 'Барэц супраць апартэіду ў ПАР, доўга сядзеў у турме. Стаў першым чорным прэзідэнтам краіны.',
    'Михаил Горбачёв': 'Генеральны сакратар ЦК КПСС, які пачаў перабудову і гласнасць. Палітыка аслабіла кантроль партыі.',
    'Маргарет Тэтчер': 'Прэм’ер-міністр Вялікабрытаніі ў 1980-х, праводзіла ліберальныя эканамічныя рэформы. Вядомая жорсткай знешняй палітыкай.',
    'Барак Обама': 'Прэзідэнт ЗША, першы афраамерыканец на гэтай пасадзе. Абраны ў 2008 годзе.',
    'Версальский мирный договор (1919 г.)': 'Мірны дагавор, падпісаны пасля Першай сусветнай. Германія прызнала вінаватым і несла цяжкія рэпарацыі.',
    'Основание Лиги Наций (1920 г.)': 'Ліга Нацый пачаў працу ў Жэневе. Яе мэтай было прадухіленне новых войнаў.',
    'Начало Великой депрессии (1929 г.)': 'Сусветны эканамічны крызіс з масавай беспрацоўцю і падзеннем вытворчасці. Пачаўся з краху на біржы ў ЗША.',
    'Приход Адольфа Гитлера к власти в Германии (1933 г.)': 'Гітлер стаў канцлерам і ўсталяваў дыктатуру ў Германіі. Пачалася падрыхтоўка да агрэсіі.',
    'Начало Второй мировой войны (1939 г.)': 'Германія напала на Польшчу, пачалася сусветная вайна. Хутка ў канфлікт уступілі многія дзяржавы.',
    'Капитуляция Германии (1945 г.)': 'Германія капітулявала безумоўна. У Еўропе вайна скончылася 8 мая 1945 года.',
    'Образование ООН (1945 г.)': 'ААН створана для захавання міру і бяспекі. У яе ўвайшлі пераможцы і многія іншыя краіны.',
    'Берлинский кризис (1961 г.)': 'СССР узвёў Берлінскую сцяну, каб спыніць адток насельніцтва. Крызіс абострыў супрацьстаянне блокаў.',
    'Падение Берлинской стены (1989 г.)': 'Сцяна, што раздзяляла Берлін, была адкрыта. Сімвалам стала падзенне камуністычных рэжымаў у Усходняй Еўропе.',
    'Распад СССР (1991 г.)': 'У канцы 1991 года СССР спыніў існаванне. Утварыліся незалежныя рэспублікі, у тым ліку Беларусь.',
    'Теракты 11 сентября в США (2001 г.)': 'Тэрарысты захапілі самалёты і атакавалі аб’екты ў ЗША. Загінулі тысячы людзей, пачалася барацьба з тэрарызмам.',
    'Вступление Китая в ВТО (2001 г.)': 'Кітай уступіў у Сусветную гандлёвую арганізацыю. Гэта паскорыла яго ўключэнне ў сусветную эканоміку.',
    'Полачане': 'Усходнеславянскае племя, якое заснавала Полачч. Жылі па рэках Заходняй Дзвіне і Дняпра.',
    'Другвины': 'Племенны саюз на тэрыторыі сучаснай Беларусі. Займаліся земляробствам, паляваннем і рамёствамі.',
    'Кривичи': 'Адно з найбольшых усходнеславянскіх племён. Іх зямлі простягаліся ад Прыбалтыкі да верхоўяў Дняпра.',
    'Полоцкое княжество': 'Старадаўняруская дзяржава са сталіцай у Полаччы. У IX–X стст. адыгрывала важную ролю ў рэгіёне.',
    'Великое княжество Литовское': 'Дзяржава літоўскіх і беларускіх зямель з цэнтрам у Вільні. Была адной з найбольшых у Еўропе.',
    'Статут ВКЛ': 'Звод законаў Вялікага Княства Літоўскага. Закрэпляў правы шляхты і парадак суда.',
    'Литвин': 'Жыхар Вялікага Княства, які размаўляў на старабеларускай. Так называлі мясцовае насельніцтва ў крыніцах.',
    'Магдебургское право': 'Права гарадскога самаўпраўлення па нямецкім узоры. Гарады атрымлівалі суд, гандаль і выбарныя органы.',
    'Шляхта': 'Шляхецкае саслоўе ў Рэчы Паспалітай. Мела палітычныя прывілеі і валодала зямлёй.',
    'Крепостное право': 'Залежнасць сялян ад памешчыка з прывязанасцю да зямлі. Распаўсюдзілася ў Рэчы Паспалітай і Расійскай імперыі.',
    'Брестская церковная уния': 'Саюз праваслаўных і уніяцкіх царкваў пад уладай папы. Прыняты ў Брэсце ў 1596 годзе.',
    'Речь Посполитая': 'Аб’яднанае дзяржава Польшчы і Вялікага Княства Літоўскага. Існавала з 1569 да канца XVIII ст.',
    'Рогнёда': 'Жонка князя Ізяслава, стала манахіняй пасля забойства мужа. Сімвал стойкасці ў полацкай гісторыі.',
    'Ефросинья Полоцкая': 'Полацкая княжна і святая, заснавала манастыр. Праславілася подвіжніцтвам і асветніцкай дзейнасцю.',
    'Франциск Скорина': 'Першы беларускі кнігадрукар і гуманіст. Выдаў Біблію і іншыя кнігі на беларускай мове.',
    'Миндовг': 'Першы кароль Літвы, які аб’яднаў літоўскія зямлі. Ахрысціўся і ўмацаваў дзяржаву.',
    'Витовт': 'Вялікі князь літоўскі, пашырыў уладанні да Чорнага мора. Супернічаў з ардой і Тэўтонскім ордэнам.',
    'Альгерд': 'Вялікі князь, умацаваў Літву і змагаўся з Тэўтонскім ордэнам. Бацька Ягайлы.',
    'Ягайло': 'Вялікі князь літоўскі і кароль Польшчы. Заключыў Крэўскую унію з Польшчай.',
    'Лев Сапега': 'Канцлер ВКЛ, адзін з аўтараў Статута 1588 года. Абараняў правы шляхты і дзяржаву.',
    'Николай Радзивилл Чёрный': 'Магнат і ваеначальнік, гетман Вялікага Княства. Удзельнічаў у войнах Рэчы Паспалітай.',
    'Симеон Полоцкий': 'Пісьменнік і прапаведнік XVII ст., настаўнік царэвіч Аляксея. Аўтар паучальных твораў.',
    'Тадеуш Костюшко': 'Польскі і амерыканскі вайсковы, герой паўстання 1794 года. Змагаўся за незалежнасць Польшчы.',
    'Кастусь Калиновский': 'Кіраўнік паўстання 1863–1864 гадоў на беларускіх зямлях. Пакараны царскім урадам.',
    'Образование Полоцкого княжества (IX в.)': 'Полацкае княства ўзнікла ў IX ст. як цэнтр усходнеславянскіх зямель. Тут склалася старажытная дзяржаўнасць.',
    'Крещение Полоцка (988 г.)': 'Князь Брачыслаў прыняў хрысціянства ад Візантыі. Хрышчэнне ўмацавала сувязі Полачча з усходнім светам.',
    'Строительство Софийского собора в Полоцке (XI в.)': 'Сабор стаў духоўным і культурным цэнтрам Полачча. Адзін з найстаражытнейшых помнікаў архітектуры Беларусі.',
    'Объединение литовских земель при Миндовге (XIII в.)': 'Міндоўг аб’яднаў племены і стварыў дзяржаву. У 1253 годзе атрымаў карану.',
    'Битва на реке Воже (1378 г.)': 'Літоўскія войскі разбілі ардынцаў на рацэ Вожы. Перамога ўмацавала незалежнасць Вялікага Княства.',
    'Грюнвальдская битва (1410 г.)': 'Аб’яднаныя сілы Польшчы і Літвы разграмілі Тэўтонскі ордэн. Вялікая перамога ў Грынвальдзе.',
    'Привилегия Вильно (1387 г.)': 'Вялікі князь Ягайла даў прывілегіі каталіцтву ў Літве. Гэта зблізіла Літву з хрысціянскай Еўропай.',
    'Принятие Статута ВКЛ (1529 г.)': 'Прыняты першы Статут — асноўны закон ВКЛ. У ім закрэпіліся правы падданых і шляхты.',
    'Люблинская уния (1569 г.)': 'Польшча і Вялікае Княства Літоўскае аб’ядналіся ў адну дзяржаву. Утворана Рэч Паспалітая.',
    'Брестская церковная уния (1596 г.)': 'Частка праваслаўных перайшла ў унію з Рымам. Мэта — умацаваць царкву і дзяржаву.',
    'Битва под Оршей (1514 г.)': 'Войскі ВКЛ разбілі масквітаў пад Оршай. Перамога ўмацавала абарону заходніх мяж.',
    'Первый раздел Речи Посполитой (1772 г.)': 'Расія, Прусія і Аўстрыя адварвалі частку зямель Рэчы Паспалітай. Пачаўся падзел аслабленай дзяржавы.',
    'Белорусская народная республика': 'Першае беларускае дзяржава, абвешчанае ў 1918 годзе. Існавала нядоўга, але сымвалізавала імкненне да незалежнасці.',
    'Западная Беларусь': 'Зямлі, што ўвайшлі ў склад Польшчы паміж сусветнымі вайнамі. У 1939 годзе ўз’ядналіся з БССР.',
    'Белорусская Советская Социалистическая Республика': 'Беларуская рэспубліка ў складзе СССР з 1919 года. Сталіца — Мінск.',
    'Коллективизация': 'Аб’яднанне сялянскіх гаспадарстваў у калгасы ў СССР. Суправаджалася паскоранай індустрыялізацыяй і цяжкасцямі ў вёсцы.',
    'Великая Отечественная война': 'Вайна СССР супраць нацысцкай Германіі 1941–1945 гадоў. На тэрыторыі Беларусі ішлі цяжкія баяві і акупацыя.',
    'Партизанское движение': 'Барацьба партызанаў і падполля супраць акупантаў. У Беларусі дзейнічалі буйныя партызанскія злучэнні.',
    'Операция «Багратион»': 'Вялікае наступленне Чырвонай Арміі летам 1944 года. Вызваліла Беларусь ад нямецкіх войск.',
    'Перестройка': 'Палітыка абнаўлення ў СССР пры Гарбачове. Уключала гласнасць і пашырэнне эканамічнай самастойнасці.',
    'Декларация о государственном суверенитете': 'Вярхоўны Савет БССР абвесціў верхавенства беларускіх законаў. Важны крок да незалежнасці.',
    'Независимость Республики Беларусь': 'Беларусь абвесціла суверэнітэт і выйшла з складу СССР. З 1991 года — самастойная дзяржава.',
    'Союзное государство': 'Саюз Беларусі і Расіі з агульнымі органамі. Створаны па дагавору 1999 года.',
    'Западная интеграция': 'Збліжэнне Беларусі з еўрапейскімі інстытутамі і рынкамі. Уключае гандаль, дагаворы і супрацоўніцтва.',
    'Вацлав Адамович': 'Дзеяч беларускага нацыянальнага руху пачатку XX ст. Удзельнічаў у стварэнні Народнай рэспублікі.',
    'Цихан Часноух': 'Старшыня Беларускай Народнай Рэспублікі ў 1918 годзе. Адзін з арганізатараў абвяшчэння незалежнасці.',
    'Янка Купала': 'Класік беларускай літаратуры, паэт і драматург. Пісаў пра лёс народа і родную зямлю.',
    'Якуб Колас': 'Класік беларускай літаратуры, прозаік і паэт. Аўтар «Сымона-музыканта» і іншых твораў.',
    'Пётр Машэраў': 'Партыйны і дзяржаўны дзеяч БССР, першы сакратар ЦК. Кіраваў рэспублікай у пасляваенныя гады.',
    'Константин Заслонов': 'Савецкі партызан, арганізатар падполля ў акупацыі. Загінуў у барацьбе з фашыстамі.',
    'Пётр Крапивницкий': 'Тэатральны дзеяч, заснавальнік беларускага прафесійнага тэатра. Кіраваў трупай у Мінску.',
    'Станислав Шушкевич': 'Старшыня Вярхоўнага Савета БССР, падпісаў Белавежскія пагадненні. Стаў першым кіраўнікам незалежнай Беларусі.',
    'Александр Лукашенко': 'Прэзідэнт Беларусі з 1994 года. Абраны на ўсеагульных выбарах.',
    'Зенон Позняк': 'Палітык і грамадскі дзеяч, супрацоўнік Беларускага народнага фронту. Выступаў за незалежнасць і дэмакратычныя рэформы.',
    'Михась Клімковіч': 'Паэт і грамадскі дзеяч, удзельнік руху за незалежнасць. Аўтар вершаў пра радзіму.',
    'Владимир Некляевич': 'Паэт, кандыдат у прэзідэнты 2010 года. Вядомы грамадзянскай лірыкай.',
    'Провозглашение Белорусской народной республики (1918 г.)': 'БНР абвешчана ў Мінску 25 сакавіка 1918 года. Першы акт беларускай дзяржаўнасці ў XX ст.',
    'Образование БССР (1919 г.)': 'Савецкая ўлада ўсталявала БССР у студзені 1919 года. Рэспубліка ўвайшла ў склад СССР.',
    'Воссоединение Западной Беларуси с БССР (1939 г.)': 'Заходняя Беларусь далучана да БССР па пакце 1939 года. Насельніцтва атрымала савецкае грамадзянства.',
    'Начало Великой Отечественной войны на территории БССР (1941 г.)': '22 чэрвеня 1941 года Германія напала на СССР. Беларусь апынулася на лініі фронту і ў акупацыі.',
    'Операция «Багратион» (1944 г.)': 'Улетку 1944 года Чырвоная Армія вызваліла большую частку Беларусі. Аперацыя паскорыла выгнанне акупантаў.',
    'Освобождение Минска (1944 г.)': '3 ліпеня 1944 года савецкія войскі ўвайшлі ў Мінск. Горад быў разбураны, пачалося аднаўленне.',
    'Чернобыльская катастрофа на территории БССР (1986 г.)': 'Аварыя на ЧАЭС закранула Гомельскую і Магілёўскую вобласці. Тысячы людзей былі эвакуіраваны.',
    'Принятие Декларации о государственном суверенитете (1990 г.)': 'Вярхоўны Савет прыняў дэкларацыю аб суверэнітэце ў 1990 годзе. Законы БССР абвешчаны вышэйшымі на яе тэрыторыі.',
    'Провозглашение независимости Республики Беларусь (1991 г.)': '19 верасня 1991 года абвешчана незалежнасць. Беларусь стала суверэннай дзяржавай.',
    'Первые президентские выборы в Беларуси (1994 г.)': 'Аляксандр Лукашэнка абраны прэзідэнтам у 1994 годзе. Прайшлі першыя прамыя ўсеагульныя выбары кіраўніка дзяржавы.',
    'Референдум об изменении Конституции (1996 г.)': 'На рэферэндуме 1996 года пашырылі паўнамоцтвы прэзідэнта. Канстытуцыю змянілі па выніках галасавання.',
  },
};
